# // {
# //     "name": "Linda Morgan-Clement",
# //     "attended": True,
# //     "is_officiant": True,
# //     "in_wedding_party": True,
# //     "is_groom": False,
# //     "is_bride": False,
# //     "inviter": "Couple",
# //     "latitude": "44.284978",
# //     "longitude": "-88.408801"
# // }

json = [
    {
        "name": "Matt Germaine",
        "attended": True,
        "is_officiant": False,
        "in_wedding_party": True,
        "is_groom": True,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.438918,
        "longitude": -79.89294
    },
    {
        "name": "Meredith Eyre",
        "attended": True,
        "is_officiant": False,
        "in_wedding_party": True,
        "is_groom": False,
        "is_bride": True,
        "inviter": "Germaine",
        "latitude": 40.438918,
        "longitude": -79.89294
    },
    {
        "name": "John Eyre",
        "attended": True,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.449996,
        "longitude": -81.933406
    },
    {
        "name": "Lee Ann Eyre",
        "attended": True,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.449996,
        "longitude": -81.933406
    },
    {
        "name": "Peter Eyre",
        "attended": True,
        "is_officiant": False,
        "in_wedding_party": True,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 33.75808,
        "longitude": -118.127501
    },
    {
        "name": "Jack Eyre",
        "attended": True,
        "is_officiant": False,
        "in_wedding_party": True,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 36.173032,
        "longitude": -86.781703
    },
    {
        "name": "Annie Hornung",
        "attended": True,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 36.173032,
        "longitude": -86.781703
    },
    {
        "name": "Morgan Jenkins",
        "attended": True,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 33.425427,
        "longitude": -117.618038
    },
    {
        "name": "Patricia Eyre",
        "attended": True,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.143255,
        "longitude": -81.505245
    },
    {
        "name": "Joseph Eyre",
        "attended": True,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 37.381187,
        "longitude": -122.104914
    },
    {
        "name": "Terri Eyre",
        "attended": True,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 37.381187,
        "longitude": -122.104914
    },
    {
        "name": "Nick Eyre",
        "attended": True,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 37.484539,
        "longitude": -122.198622
    },
    {
        "name": "Stephanie Eyre",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 37.838099,
        "longitude": -122.249716
    },
    {
        "name": "James Eyre",
        "attended": True,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 33.944461,
        "longitude": -84.210969
    },
    {
        "name": "Paula Volino",
        "attended": True,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 33.944461,
        "longitude": -84.210969
    },
    {
        "name": "Patrick Eyre",
        "attended": True,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 29.469866,
        "longitude": -98.377344
    },
    {
        "name": "Katie Volino",
        "attended": True,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 33.804845,
        "longitude": -84.264028
    },
    {
        "name": "Jeffrey Eyre",
        "attended": True,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 35.799064,
        "longitude": -81.324618
    },
    {
        "name": "Linda Eyre",
        "attended": True,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 35.799064,
        "longitude": -81.324618
    },
    {
        "name": "Allyson Avila",
        "attended": True,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 35.799064,
        "longitude": -81.324618
    },
    {
        "name": "Glen Fitzjerrell",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.860179,
        "longitude": -87.806721
    },
    {
        "name": "Jane Fitzjerrell",
        "attended": True,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.860179,
        "longitude": -87.806721
    },
    {
        "name": "Barbara Everett",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 37.321326,
        "longitude": -79.943385
    },
    {
        "name": "Richard Eyre",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.121477,
        "longitude": -81.448117
    },
    {
        "name": "Cara Eyre",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.860179,
        "longitude": -87.806721
    },
    {
        "name": "Trish Rucker",
        "attended": True,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.034336,
        "longitude": -81.393071
    },
    {
        "name": "Ms. Carolyn Naso",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.931661,
        "longitude": -81.341082
    },
    {
        "name": "Rich Eyre",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.085152,
        "longitude": -81.405818
    },
    {
        "name": "Kathy Eyre",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.085152,
        "longitude": -81.405818
    },
    {
        "name": "Michael Bloom",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.951448,
        "longitude": -81.3876
    },
    {
        "name": "Anela Bloom",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.951448,
        "longitude": -81.3876
    },
    {
        "name": "Mr. Shane Stewart",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 36.395295,
        "longitude": -82.524019
    },
    {
        "name": "Mrs. Shane Stewart",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 36.395295,
        "longitude": -82.524019
    },
    {
        "name": "Wayne Koide",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 37.909767,
        "longitude": -122.381799
    },
    {
        "name": "Susan Koide",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 37.909767,
        "longitude": -122.381799
    },
    {
        "name": "Janet Sheffler",
        "attended": True,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.466473,
        "longitude": -81.837309
    },
    {
        "name": "Lynne Megerian",
        "attended": True,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.48066,
        "longitude": -81.512693
    },
    {
        "name": "Cliff Megerian",
        "attended": True,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.48066,
        "longitude": -81.512693
    },
    {
        "name": "Caroline Megerian",
        "attended": True,
        "is_officiant": False,
        "in_wedding_party": True,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.48066,
        "longitude": -81.512693
    },
    {
        "name": "Andrew Megerian",
        "attended": True,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.761885,
        "longitude": -73.985413
    },
    {
        "name": "Mark Megerian",
        "attended": True,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.497582,
        "longitude": -81.596917
    },
    {
        "name": "Tom McClave",
        "attended": True,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": "41.540836",
        "longitude": "-81.42802"
    },
    {
        "name": "Mrs. McClave",
        "attended": True,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.540836,
        "longitude": -81.42802
    },
    {
        "name": "Michael McClave",
        "attended": True,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.562172,
        "longitude": -81.455024
    },
    {
        "name": "Julie McClave",
        "attended": True,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.562172,
        "longitude": -81.455024
    },
    {
        "name": "Mackenzie McClave",
        "attended": True,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.562172,
        "longitude": -81.455024
    },
    {
        "name": "Ellie McClave",
        "attended": True,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.562172,
        "longitude": -81.455024
    },
    {
        "name": "Logan McClave",
        "attended": True,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.562172,
        "longitude": -81.455024
    },
    {
        "name": "John Elliott",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.567419,
        "longitude": -81.364011
    },
    {
        "name": "Lauren Elliott",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.567419,
        "longitude": -81.364011
    },
    {
        "name": "Lindsey Elliott",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.567419,
        "longitude": -81.364011
    },
    {
        "name": "Johnny Elliott",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.567419,
        "longitude": -81.364011
    },
    {
        "name": "Gary McClave",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 35.649074,
        "longitude": -78.724406
    },
    {
        "name": "Sandi McClave",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 35.649074,
        "longitude": -78.724406
    },
    {
        "name": "Jim McClave",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 38.333042,
        "longitude": -77.742698
    },
    {
        "name": "Mrs. Jim McClave",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 38.333042,
        "longitude": -77.742698
    },
    {
        "name": "Peyton McClave",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 38.333042,
        "longitude": -77.742698
    },
    {
        "name": "Steven McClave",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.129048,
        "longitude": -81.510644
    },
    {
        "name": "Maggie McClave",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.129048,
        "longitude": -81.510644
    },
    {
        "name": "Eileen Moran",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.462537,
        "longitude": -82.007593
    },
    {
        "name": "Chris Essig",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.450182,
        "longitude": -81.9326
    },
    {
        "name": "Mary Essig",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.450182,
        "longitude": -81.9326
    },
    {
        "name": "John Wanhainen",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.467344,
        "longitude": -81.892602
    },
    {
        "name": "Mrs. John Wanhainen",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.467344,
        "longitude": -81.892602
    },
    {
        "name": "Chris Alibeckoff",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.489092,
        "longitude": -81.838891
    },
    {
        "name": "Dominique Alibeckoff",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.489092,
        "longitude": -81.838891
    },
    {
        "name": "Rick Lehtinen",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.810283,
        "longitude": -81.94282
    },
    {
        "name": "Marcy Campbell",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.810283,
        "longitude": -81.94282
    },
    {
        "name": "Whitaker Campbell-Lehtinen",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.810283,
        "longitude": -81.94282
    },
    {
        "name": "Lily Campbell-Lehtinen",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.810283,
        "longitude": -81.94282
    },
    {
        "name": "Jeff Roche",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.810317,
        "longitude": -81.943171
    },
    {
        "name": "Mrs. Jeff Roche",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.810317,
        "longitude": -81.943171
    },
    {
        "name": "Dale Jarvis",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.810072,
        "longitude": -81.94257
    },
    {
        "name": "Janet Jarvis",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.810072,
        "longitude": -81.94257
    },
    {
        "name": "The McCusker-Johnson Family",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.810071,
        "longitude": -81.942677
    },
    {
        "name": "Jim Pyers",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.810103,
        "longitude": -81.942878
    },
    {
        "name": "Mrs. Jim Pyers",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.810103,
        "longitude": -81.942878
    },
    {
        "name": "Jorge Scheirer",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.306257,
        "longitude": -75.841368
    },
    {
        "name": "Tracy Scheirer",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.306257,
        "longitude": -75.841368
    },
    {
        "name": "The Sterling Family",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 35.985783,
        "longitude": -86.789812
    },
    {
        "name": "Greg Runser",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.021158,
        "longitude": -83.18109
    },
    {
        "name": "Mrs. Greg Runser",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.021158,
        "longitude": -83.18109
    },
    {
        "name": "Jeff Peterson",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 48.25428,
        "longitude": -101.420182
    },
    {
        "name": "Diana Peterson",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 48.25428,
        "longitude": -101.420182
    },
    {
        "name": "Rhett Weaver",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 34.653225,
        "longitude": -83.563859
    },
    {
        "name": "Tammy Weaver",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 34.653225,
        "longitude": -83.563859
    },
    {
        "name": "Leslie Weaver",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 36.174426,
        "longitude": -86.740369
    },
    {
        "name": "Manuel Steffas",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.455551,
        "longitude": -81.939381
    },
    {
        "name": "Maggie Steffas",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.455551,
        "longitude": -81.939381
    },
    {
        "name": "Cindy McArdle",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.456043,
        "longitude": -81.966038
    },
    {
        "name": "Kent Murphy",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.810119,
        "longitude": -81.943024
    },
    {
        "name": "Joyce Murphy",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.810119,
        "longitude": -81.943024
    },
    {
        "name": "Rose Marie Baab",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.809867,
        "longitude": -81.943798
    },
    {
        "name": "Matthew Bednarczyk",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 42.506646,
        "longitude": -83.187314
    },
    {
        "name": "Donna Bednarczyk",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 42.506646,
        "longitude": -83.187314
    },
    {
        "name": "Roger Blake",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 42.492168,
        "longitude": -83.167306
    },
    {
        "name": "Jen Blake",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 42.492168,
        "longitude": -83.167306
    },
    {
        "name": "Kevin Brener",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 38.99499,
        "longitude": -77.584997
    },
    {
        "name": "Jennifer Brener",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 38.99499,
        "longitude": -77.584997
    },
    {
        "name": "Kendall Brener",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 38.99499,
        "longitude": -77.584997
    },
    {
        "name": "Kayleigh Brener",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 38.99499,
        "longitude": -77.584997
    },
    {
        "name": "Robert Brus",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 42.496843,
        "longitude": -83.179307
    },
    {
        "name": "Diane Brus",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 42.496843,
        "longitude": -83.179307
    },
    {
        "name": "Linda Conway",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 39.924151,
        "longitude": -74.149532
    },
    {
        "name": "Henry Cook",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 35.413615,
        "longitude": -80.896896
    },
    {
        "name": "Susan Cook",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 35.413615,
        "longitude": -80.896896
    },
    {
        "name": "Gabrielle Gubernat",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.707876,
        "longitude": -74.654131
    },
    {
        "name": "Peter Costales",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.707876,
        "longitude": -74.654131
    },
    {
        "name": "Peter DeMarois",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 42.572941,
        "longitude": -83.196501
    },
    {
        "name": "Amy DeMarois",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 42.572941,
        "longitude": -83.196501
    },
    {
        "name": "Christine Germaine",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 35.90718,
        "longitude": -78.991359
    },
    {
        "name": "David Germaine",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 42.341952,
        "longitude": -83.409965
    },
    {
        "name": "Frank Gubernat",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.661899,
        "longitude": -74.54301
    },
    {
        "name": "Blair Harrold",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 35.968721,
        "longitude": -77.857901
    },
    {
        "name": "Alice Harrold",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 35.968721,
        "longitude": -77.857901
    },
    {
        "name": "Robert Holbrook",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 35.688884,
        "longitude": -78.441918
    },
    {
        "name": "Mrs. Robert Holbrook",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 35.688884,
        "longitude": -78.441918
    },
    {
        "name": "Harry Holloway",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 39.163293,
        "longitude": -78.135485
    },
    {
        "name": "Mrs. Harry Holloway",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 39.163293,
        "longitude": -78.135485
    },
    {
        "name": "Fred Hrinuk",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.715111,
        "longitude": -74.316927
    },
    {
        "name": "Mrs. Fred Hrinuk",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.715111,
        "longitude": -74.316927
    },
    {
        "name": "Arlene Lofgren",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 39.045236,
        "longitude": -77.46097
    },
    {
        "name": "Courtney Lofgren",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 38.884812,
        "longitude": -77.117943
    },
    {
        "name": "Daniel Moran",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 42.496606,
        "longitude": -83.192814
    },
    {
        "name": "Mrs. Daniel Moran",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 42.496606,
        "longitude": -83.192814
    },
    {
        "name": "JuanLuis Periche-Feliz and Family",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 35.069581,
        "longitude": -80.791429
    },
    {
        "name": "Marianne Quigley",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 42.629474,
        "longitude": -83.223356
    },
    {
        "name": "David Dubay",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 42.629474,
        "longitude": -83.223356
    },
    {
        "name": "Scott Reese",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 36.234483,
        "longitude": -81.748435
    },
    {
        "name": "Kim Reese",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 36.234483,
        "longitude": -81.748435
    },
    {
        "name": "Catherine Ronan",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 42.461488,
        "longitude": -82.955835
    },
    {
        "name": "Timothy Saunders",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 42.497652,
        "longitude": -83.201952
    },
    {
        "name": "Lori Saunders",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 42.497652,
        "longitude": -83.201952
    },
    {
        "name": "Elizabeth Spainhour",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 36.142802,
        "longitude": -79.86981
    },
    {
        "name": "Stacy Street",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 36.142802,
        "longitude": -79.86981
    },
    {
        "name": "Gregory Swerdlow",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.426256,
        "longitude": -74.649346
    },
    {
        "name": "Adrienne Swerdlow",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.426256,
        "longitude": -74.649346
    },
    {
        "name": "Alexis Swerdlow",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.426256,
        "longitude": -74.649346
    },
    {
        "name": "Justin Swerdlow",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.426256,
        "longitude": -74.649346
    },
    {
        "name": "Jeffrey Thomasson",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 36.133484,
        "longitude": -78.961754
    },
    {
        "name": "Beth Thomasson",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 36.133484,
        "longitude": -78.961754
    },
    {
        "name": "Flo Todd",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 27.645144,
        "longitude": -80.481026
    },
    {
        "name": "Barbara Wujciak",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 35.91855,
        "longitude": -79.020357
    },
    {
        "name": "Edwin Wujciak",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 26.605269,
        "longitude": -80.157254
    },
    {
        "name": "Alice Wujciak",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 26.605269,
        "longitude": -80.157254
    },
    {
        "name": "James Wujciak",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.921692,
        "longitude": -74.246492
    },
    {
        "name": "Linda Wujciak",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 35.148801,
        "longitude": -80.765606
    },
    {
        "name": "Martine Gubernat",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.603666,
        "longitude": -74.616254
    },
    {
        "name": "Ms. Susan A. Zega",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.603666,
        "longitude": -74.616254
    },
    {
        "name": "Tom McKarns",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 42.223011,
        "longitude": -83.772993
    },
    {
        "name": "Lisa McKarns",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 42.223011,
        "longitude": -83.772993
    },
    {
        "name": "Andrew Badger",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 32.845952,
        "longitude": -97.250075
    },
    {
        "name": "Jake Boca",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.459991,
        "longitude": -79.948811
    },
    {
        "name": "Derrick Callahan",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.459991,
        "longitude": -79.948811
    },
    {
        "name": "Joey Smerud",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 43.804889,
        "longitude": -91.224185
    },
    {
        "name": "Jenni Smerud",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 43.804889,
        "longitude": -91.224185
    },
    {
        "name": "Alex Chabraja",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 30.320725,
        "longitude": -97.736477
    },
    {
        "name": "Gabi Berrios",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 30.320725,
        "longitude": -97.736477
    },
    {
        "name": "James Coddington",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 39.403528,
        "longitude": -76.956267
    },
    {
        "name": "Gwen Coddington",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 39.403528,
        "longitude": -76.956267
    },
    {
        "name": "Emily Corwin",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 42.546329,
        "longitude": -83.19802
    },
    {
        "name": "Joe Thornton",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 42.546329,
        "longitude": -83.19802
    },
    {
        "name": "Jacob Duchan",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 42.481369,
        "longitude": -83.178658
    },
    {
        "name": "Aimon Dwan",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 44.937071,
        "longitude": -93.141799
    },
    {
        "name": "Rafa Auqui",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 44.937071,
        "longitude": -93.141799
    },
    {
        "name": "Anna Easterday",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.094632,
        "longitude": -83.177962
    },
    {
        "name": "Melanie Fraser",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 42.447629,
        "longitude": -76.49582
    },
    {
        "name": "Tim Fraser",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 42.447629,
        "longitude": -76.49582
    },
    {
        "name": "Umberto Gordon",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 38.362899,
        "longitude": -76.397508
    },
    {
        "name": "Colleen Gordon",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 38.362899,
        "longitude": -76.397508
    },
    {
        "name": "Fiona Gordon",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 38.362899,
        "longitude": -76.397508
    },
    {
        "name": "Ed Hebb",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.784741,
        "longitude": -81.958041
    },
    {
        "name": "Linda Hebb",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.784741,
        "longitude": -81.958041
    },
    {
        "name": "Jeremy Hernandez-Hermann",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 42.289176,
        "longitude": -85.626543
    },
    {
        "name": "Dalia Hernandez-Hermann",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 42.289176,
        "longitude": -85.626543
    },
    {
        "name": "Kirstin Holm",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 44.944439,
        "longitude": -93.294867
    },
    {
        "name": "Adrienne James",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.395957,
        "longitude": -82.657427
    },
    {
        "name": "Kelsey Jandrey",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 43.138828,
        "longitude": -87.911931
    },
    {
        "name": "Emily Lanzola Mariner",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.36023,
        "longitude": -82.045915
    },
    {
        "name": "Charles Kammer",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.830699,
        "longitude": -81.895377
    },
    {
        "name": "Ryan Kish",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.473002,
        "longitude": -79.924684
    },
    {
        "name": "Taylor Thorp",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.473002,
        "longitude": -79.924684
    },
    {
        "name": "Susan Kuecker",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 44.533998,
        "longitude": -71.998391
    },
    {
        "name": "Jim Grahm",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 44.533998,
        "longitude": -71.998391
    },
    {
        "name": "Grace Kramer",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 44.956737,
        "longitude": -93.283865
    },
    {
        "name": "Max Kramer",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 44.956737,
        "longitude": -93.283865
    },
    {
        "name": "Blake Larson",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.476022,
        "longitude": -81.510945
    },
    {
        "name": "Miles Larson",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.476022,
        "longitude": -81.510945
    },
    {
        "name": "Amy Larson",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.476022,
        "longitude": -81.510945
    },
    {
        "name": "Matt Larson",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.476022,
        "longitude": -81.510945
    },
    {
        "name": "Kati McArdle",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 35.914176,
        "longitude": -79.080394
    },
    {
        "name": "Michael Jones",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 35.914176,
        "longitude": -79.080394
    },
    {
        "name": "David McConnell",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.843143,
        "longitude": -81.971713
    },
    {
        "name": "Cathy McConnell",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.843143,
        "longitude": -81.971713
    },
    {
        "name": "Bri McIntyre",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.819357,
        "longitude": -81.368852
    },
    {
        "name": "Shane McIntyre",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.819357,
        "longitude": -81.368852
    },
    {
        "name": "Noelle McIntyre",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.819357,
        "longitude": -81.368852
    },
    {
        "name": "Wes Myers",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.187232,
        "longitude": -85.804639
    },
    {
        "name": "Jonell Myers",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.187232,
        "longitude": -85.804639
    },
    {
        "name": "Keely Pearce",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 39.714287,
        "longitude": -82.593532
    },
    {
        "name": "Bob Randall",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.831847,
        "longitude": -81.947456
    },
    {
        "name": "Bobbie Randall",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.831847,
        "longitude": -81.947456
    },
    {
        "name": "Ben Robertson",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 43.174827,
        "longitude": -73.061768
    },
    {
        "name": "Alea Safier",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 42.376977,
        "longitude": -71.14965
    },
    {
        "name": "David Freund",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 42.376977,
        "longitude": -71.14965
    },
    {
        "name": "Kelsey Scott",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.026996,
        "longitude": -83.018517
    },
    {
        "name": "Andy Patt",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.026996,
        "longitude": -83.018517
    },
    {
        "name": "Edmund Shi",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.89522,
        "longitude": -81.116438
    },
    {
        "name": "Kate Sickles",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 42.220214,
        "longitude": -83.775547
    },
    {
        "name": "Michael Sickles",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 42.220214,
        "longitude": -83.775547
    },
    {
        "name": "Eliza Sickles",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 42.220214,
        "longitude": -83.775547
    },
    {
        "name": "Whitney Sims",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.466132,
        "longitude": -81.540702
    },
    {
        "name": "Maria Steffas",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.463629,
        "longitude": -81.858075
    },
    {
        "name": "Cindy Tran",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 37.534154,
        "longitude": -122.035414
    },
    {
        "name": "Stephen Tryban",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 43.59557,
        "longitude": -84.760607
    },
    {
        "name": "Brian Tucker",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 36.120617,
        "longitude": -115.067854
    },
    {
        "name": "Elliott Valentine",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 43.083665,
        "longitude": -89.361001
    },
    {
        "name": "Katelyn French",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 43.083665,
        "longitude": -89.361001
    },
    {
        "name": "Alejandra Vargas",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 33.402866,
        "longitude": -90.890464
    },
    {
        "name": "Amilcar Vargas",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 33.402866,
        "longitude": -90.890464
    },
    {
        "name": "Dan Vedda",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 41.339548,
        "longitude": -81.905003
    },
    {
        "name": "Steve Voelker",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.828479,
        "longitude": -80.25314
    },
    {
        "name": "Samantha Voelker",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Germaine",
        "latitude": 40.828479,
        "longitude": -80.25314
    },
    {
        "name": "Linda Morgan-Clement",
        "attended": True,
        "is_officiant": True,
        "in_wedding_party": True,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Couple",
        "latitude": 44.284978,
        "longitude": -88.408801
    },
    {
        "name": "Mike Clement",
        "attended": False,
        "is_officiant": False,
        "in_wedding_party": False,
        "is_groom": False,
        "is_bride": False,
        "inviter": "Couple",
        "latitude": 44.284978,
        "longitude": -88.408801
    }
]

guests = []

for guest in json:
    formatted_guest = {}
    formatted_guest["type"] = "Feature"
    formatted_guest["properties"] = {
        "name": guest["name"],
        "attended": guest["attended"],
        "is_officiant": guest["is_officiant"],
        "in_wedding_party": guest["in_wedding_party"],
        "is_groom": guest["is_groom"],
        "is_bride": guest["is_bride"],
        "inviter": guest["inviter"]
    }
    formatted_guest["geometry"] = {
        "type": "Point",
        "coordinates": [
            guest["longitude"],
            guest["latitude"]
        ]
    }
    guests.append(formatted_guest)

print(guests)
